allowBuilds:
  esbuild: true

minimumReleaseAgeExclude:
  - "@vitest/coverage-istanbul@5.0.0"
  - "@vitest/coverage-v8@5.0.0"
  - "@vitest/mocker@5.0.0"
  - "@vitest/spy@5.0.0"
  - vitest@5.0.0

overrides:
  "@vitest/coverage-v8>ast-v8-to-istanbul": ./
